apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dynaplan-api
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: dynaplan-route
spec:
  ingressClassName: nginx
  rules:
  - host: dynaplan.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dynaplan-api
            port:
              number: 80

